refactor: refactor the entire project
readthedocs-fr/read-the-bin pull request #1
Opened 2020-12-12 21:57 UTC by Mesteery

2020-12-12 23:06 UTC, Aakodal requested changes
Bien que je sois d'accord avec la majorité de ta PR (beaucoup d'étourderies que j'ai laissées, shame on me), j'ai remarqué certains trucs qui me chiffonent (cf commentaires), en particulier le fait que tu aies merge /events/file/, /events/snippet/ et /events/message/.

Originellement, j'avais bien prévu de tout faire dans un seul fichier, mais je me suis rendu compte que j'avais du mal à savoir dans quel cas j'étais. Selon moi, cette séparation permet d'avoir un event pour une "feature" en particulier ; ça permet ainsi d'avoit quelque chose de clair et aéré, et de savoir que je modifie X comportement.

2020-12-12 23:06 UTC, Aakodal commented on src/helpers/sendBinEmbed.ts
> +	const collector = await botMessage.awaitReactions(filter, { max: 1, time: 20000 });
C'est une question de coding style et d'habitude, personnellement j'aime bien passer par la multiplication puisque j'ai directement la durée en secondes sous les yeux, m'enfin

2020-12-12 23:06 UTC, Aakodal commented on src/index.ts
> +client.init();
C'était originellement pour éviter que l'IDE gueule quant à une promise non-traitée

2020-12-13 07:25 UTC, Mesteery commented
> Bien que je sois d'accord avec la majorité de ta PR (beaucoup d'étourderies que j'ai laissées, shame on me), j'ai remarqué certains trucs qui me chiffonent (cf commentaires), en particulier le fait que tu aies merge /events/file/, /events/snippet/ et /events/message/.
> 
> Originellement, j'avais bien prévu de tout faire dans un seul fichier, mais je me suis rendu compte que j'avais du mal à savoir dans quel cas j'étais. Selon moi, cette séparation permet d'avoir un event pour une "feature" en particulier ; ça permet ainsi d'avoit quelque chose de clair et aéré, et de savoir que je modifie X comportement.

Je suis pas trop d'accord avec toi sur ce coup là, je trouve ça horrible d'utiliser les événements plur ça, c'est overkill et inutile. De base, j'ai fais une  fichiers dans le dossier `message` : `file.ts` et `snippet.ts`, chaque fichier contentait la fonction qui traitait le message (comme dans l'event), ces fonctions étaient directement appelées dans l'évènement `message`. Mais, je me suis rendu compte, que ça valait pas vraiment le coup, de les séparer en plusieurs fichiers, étant donné qu'elles sont assez petites. Donc j'ai décider de les mettre directement dans les `if`. Après, si tu préfères les séparer pour une raison particulière, il n'y a pas de problème. Si tu veux vraiment les séparer, on peut créer un fichier `x.ts` dans le dossier `message` qui rassemble les 2 fonctions, qui sont importés et ensuite appelés dans l'évènement. Sinon, pour les gérer via le système d'événement, je suis totalement contre.

2020-12-13 07:27 UTC, Mesteery commented on src/index.ts
> +client.init();
Je pense pas que ce soit la meilleure solution pour éviter que ton IDE gueule. Essaye de trouver un paramètre.
(Mon IDE gueule pas)

2020-12-13 07:28 UTC, Mesteery commented on src/helpers/sendBinEmbed.ts
> +	const collector = await botMessage.awaitReactions(filter, { max: 1, time: 20000 });
Personnellement, je fais comme toi, mais pour des plus grandes durées. Dit-mol si tu préfères comme.

2020-12-13 07:29 UTC, Mesteery commented on src/helpers/sendBinEmbed.ts
> +		.setAuthor(message.author.tag, message.author.displayAvatarURL({ dynamic: true }))
J'ai pas vraiment pensé à ça, c'est vrai je suis d'accord.

2020-12-13 07:32 UTC, Mesteery commented on src/helpers/codeBlock.ts
> +		result = result.replace(blockString, `${bin instanceof Error ? bin.message : bin} `);
J'ai tester le bot avant de PR. Il me semble que j'avais mis plusieurs (même) blocs de codes et ça avait marché.

2020-12-13 07:33 UTC, Mesteery commented on src/classes/Client.ts
> +const noop = (): void => {};
Y a rien d'utile. C'est juste mieux que de faire la fonction 2 fois.

2020-12-13 08:12 UTC, Mesteery commented on src/helpers/codeBlock.ts
> +		result = result.replace(blockString, `${bin instanceof Error ? bin.message : bin} `);
Eh bien, sache que si, j'ai raison !
Tu détectais mal les doublons : car il peut y avoir des espaces et/ou des new lines. Donc le bloc de code peut être ajouter alors qu'il est déjà ajouté. Donc j'ai raison dans le cas où ça fonctionne correctement (oui et non).
Je corrige ce problème.

2020-12-13 09:38 UTC, Aakodal commented on src/helpers/codeBlock.ts
> +		result = result.replace(blockString, `${bin instanceof Error ? bin.message : bin} `);
Oui, depuis le passage sous marked, les blocs avaient le newline, mais du coup c'était considéré comme des blocs vraiment différents (avec et sans newline du coup)

2020-12-13 09:39 UTC, Aakodal commented on src/classes/Client.ts
> +const noop = (): void => {};
Je trouve ça assez embrouillant, surtout si on est en plein milieu du code et qu'on se demande ce à quoi correspond noop

2020-12-13 09:44 UTC, Mesteery commented on src/classes/Client.ts
> +const noop = (): void => {};
Je préfère ça que des répétitions perso, sinon on peut le renommer

2020-12-13 09:54 UTC, Aakodal commented on src/classes/Client.ts
> +const noop = (): void => {};
Why not "nil" ou même juste "void_"/"null_" (c'est pas conventionnel mais je trouve pas ça gênant, au pire "fVoid"/"fNull")

2020-12-13 09:59 UTC, Aakodal approved these changes

2020-12-13 10:04 UTC, merged