docs(readme): improve doc
readthedocs-fr/read-the-bin pull request #19
Opened 2021-02-01 20:00 UTC by Mesteery

2021-02-01 20:03 UTC, Aakodal requested changes

2021-02-01 20:03 UTC, Aakodal commented on README.md
> +git commit -m "type(optionnal scope): short message
Peut-être plus quelque chose dans le style 
```suggestion
git commit -m "conventional commit message"
``` (et puis tu feras gaffe t'as oublié un `"`)

2021-02-01 20:05 UTC, Mesteery commented on README.md
> +git commit -m "type(optionnal scope): short message
(Le " est plus bas)

2021-02-01 20:07 UTC, Aakodal commented on README.md
> +git commit -m "type(optionnal scope): short message
Ahah ouais. Je suis juste aveugle.

2021-02-03 19:46 UTC, Aakodal commented
Si c'est bon, passe-le en ready for review

2021-02-03 19:47 UTC, Mesteery commented
Ah ouai ? Je trouve ça super dirty. Enfin pas assez complet je trouve

2021-02-03 19:48 UTC, Aakodal commented
Le but de cette PR-ci c'était d'ajouter du texte sur la collaboration ; d'autres viendront compléter, ajouter, modifier, que sais-je.

2021-02-03 20:08 UTC, Aakodal approved these changes

2021-02-03 20:09 UTC, merged